spring:
  profiles:
    active:dev
---
spring:
  profiles: dev
  application:
    name: microserivcecloud-config-he-dev
---
spring:
  profiles: test
  application:
    name: microserivcecloud-config-he-test

 #请保存为utf-8格式
