#eureka配置
eurekaservice:
  serviceUrl: http://localhost:8099/eureka/ #http://47.105.216.103:8761/eureka/
#  serviceUrl: http://172.30.128.15:8099/eureka/ #http://47.105.216.103:8761/eureka/

otherservice:
  userUrl: http://localhost:8088/auth #http://localhost:8089 #用户服务
#  userUrl: http://172.30.128.16:8088/auth #http://localhost:8089 #用户服务
  zipkinUrl: http://localhost:9411/ #zipkin服务


#配置邮件发送信息
spring:
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: leon_wzl@qq.com
    password: qjvwoelsomqfedhj
    port: 25
    protocol: smtp
server:
  port: 8000
